
version: '3.8'
services:
  app:
    image: 't_medical_center_system:latest'
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    container_name: db
    image: 'postgres:13.4'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"


#
#version: '3.8'
#services:
#  app:
#    image: 'test-img'
#    container_name: app
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#  db:
#    container_name: db
#    image: 'postgres:13.4'
#    environment:
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=database
#    ports:
#      - "5432:5432"


