version: '3.8'
services:
  app:
#    image: 'sample'
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
  db:
    container_name: db
    image: 'postgres:13.4'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.9.8'
    ports:
      - "5672:5672"
      - "15672:15672"
#  app2:
#    container_name: app2
#    build:
#      dockerfile: /docker/app2/Dockerfile
#    ports:
#      - "8040:8040"
#      - "9990:9990"



